= Security roles

== Blue team

=== Security Analyst
Responsible for maintaining the security of an organisation's data

* analyse the cyber-security of the company
* reports about the safety of the networks, document security issues, measures taken in response
* develop security plans, incorporate research on new attack tools and trends, and measures needed across teams to maintain data security

=== Security Engineer
Design, monitor and maintain security controls, networks, and systems to help prevent cyberattacks

* test and screen security measures across software
* monitor networks and reports to update systems and mitigate vulnerabilities
* identify and implement systems needed for optimal security

=== Incident Responder
Identifies and mitigates attacks whilst an attackers operations are still unfolding

* develop and adopt actionable incident response plan
* maintain strong security best practices and support incident response measures
* post-incident reporting and preparation of future attacks

=== Digital Forensics Examiner
Responsible for using digital forensics to investigate incidents and crimes

* collect digital evidence while observing legal procedures
* analyse digital evidence to find answers related to the case
* document and report on the case

=== Malware Analyst / Reverse Engineer
Analyses all types of malware to learn more about how they work and what they do

* static analysis of malicious programs (reverse engineering)
* dynamic analysis of malwares by observing their activities in a controlled environment
* document and report all findings

== Red team

=== Penetration Tester
Responsible for testing technology products for security loopholes

* test computer systems, networks, and web-based applications
* perform security assessments, audits and analyse policies
* evaluate and report on insights, recommend actions for attack prevention

=== Red Teamer
Plays the role of an adversary, attacking an organisation and providing feedback from an enemies perspective

* emulate the role of a threat actor to uncover exploitable vulnerabilities, maintain access and avoid detection
* assess organisations' security controls, threat intelligence, and incident response procedures
* evaluate and report on insights, with actionable data for companies to avoid real-world instances
